version: '3.9'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - bff-network

  app:
    build: .
    container_name: BFF
    ports:
      - "3000:3000"
    networks:
      - bff-network
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: npm run start:dev
    volumes:
      - .:/usr/src/app

networks: 
  bff-network: